# coding: utf-8

"""
    Argo

    Python client for Argo Workflows  # noqa: E501

    OpenAPI spec version: master
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GrpcGatewayRuntimeStreamError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'details': 'list[GoogleProtobufAny]',
        'grpc_code': 'int',
        'http_code': 'int',
        'http_status': 'str',
        'message': 'str'
    }

    attribute_map = {
        'details': 'details',
        'grpc_code': 'grpc_code',
        'http_code': 'http_code',
        'http_status': 'http_status',
        'message': 'message'
    }

    def __init__(self, details=None, grpc_code=None, http_code=None, http_status=None, message=None):  # noqa: E501
        """GrpcGatewayRuntimeStreamError - a model defined in Swagger"""  # noqa: E501

        self._details = None
        self._grpc_code = None
        self._http_code = None
        self._http_status = None
        self._message = None
        self.discriminator = None

        if details is not None:
            self.details = details
        if grpc_code is not None:
            self.grpc_code = grpc_code
        if http_code is not None:
            self.http_code = http_code
        if http_status is not None:
            self.http_status = http_status
        if message is not None:
            self.message = message

    @property
    def details(self):
        """Gets the details of this GrpcGatewayRuntimeStreamError.  # noqa: E501


        :return: The details of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :rtype: list[GoogleProtobufAny]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this GrpcGatewayRuntimeStreamError.


        :param details: The details of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :type: list[GoogleProtobufAny]
        """

        self._details = details

    @property
    def grpc_code(self):
        """Gets the grpc_code of this GrpcGatewayRuntimeStreamError.  # noqa: E501


        :return: The grpc_code of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :rtype: int
        """
        return self._grpc_code

    @grpc_code.setter
    def grpc_code(self, grpc_code):
        """Sets the grpc_code of this GrpcGatewayRuntimeStreamError.


        :param grpc_code: The grpc_code of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :type: int
        """

        self._grpc_code = grpc_code

    @property
    def http_code(self):
        """Gets the http_code of this GrpcGatewayRuntimeStreamError.  # noqa: E501


        :return: The http_code of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :rtype: int
        """
        return self._http_code

    @http_code.setter
    def http_code(self, http_code):
        """Sets the http_code of this GrpcGatewayRuntimeStreamError.


        :param http_code: The http_code of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :type: int
        """

        self._http_code = http_code

    @property
    def http_status(self):
        """Gets the http_status of this GrpcGatewayRuntimeStreamError.  # noqa: E501


        :return: The http_status of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :rtype: str
        """
        return self._http_status

    @http_status.setter
    def http_status(self, http_status):
        """Sets the http_status of this GrpcGatewayRuntimeStreamError.


        :param http_status: The http_status of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :type: str
        """

        self._http_status = http_status

    @property
    def message(self):
        """Gets the message of this GrpcGatewayRuntimeStreamError.  # noqa: E501


        :return: The message of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this GrpcGatewayRuntimeStreamError.


        :param message: The message of this GrpcGatewayRuntimeStreamError.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GrpcGatewayRuntimeStreamError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GrpcGatewayRuntimeStreamError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
