# coding: utf-8

"""
    Argo

    Python client for Argo Workflows  # noqa: E501

    OpenAPI spec version: master
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1ArtifactoryArtifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'artifactory_auth': 'V1alpha1ArtifactoryAuth',
        'url': 'str'
    }

    attribute_map = {
        'artifactory_auth': 'artifactoryAuth',
        'url': 'url'
    }

    def __init__(self, artifactory_auth=None, url=None):  # noqa: E501
        """V1alpha1ArtifactoryArtifact - a model defined in Swagger"""  # noqa: E501

        self._artifactory_auth = None
        self._url = None
        self.discriminator = None

        if artifactory_auth is not None:
            self.artifactory_auth = artifactory_auth
        if url is not None:
            self.url = url

    @property
    def artifactory_auth(self):
        """Gets the artifactory_auth of this V1alpha1ArtifactoryArtifact.  # noqa: E501


        :return: The artifactory_auth of this V1alpha1ArtifactoryArtifact.  # noqa: E501
        :rtype: V1alpha1ArtifactoryAuth
        """
        return self._artifactory_auth

    @artifactory_auth.setter
    def artifactory_auth(self, artifactory_auth):
        """Sets the artifactory_auth of this V1alpha1ArtifactoryArtifact.


        :param artifactory_auth: The artifactory_auth of this V1alpha1ArtifactoryArtifact.  # noqa: E501
        :type: V1alpha1ArtifactoryAuth
        """

        self._artifactory_auth = artifactory_auth

    @property
    def url(self):
        """Gets the url of this V1alpha1ArtifactoryArtifact.  # noqa: E501


        :return: The url of this V1alpha1ArtifactoryArtifact.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this V1alpha1ArtifactoryArtifact.


        :param url: The url of this V1alpha1ArtifactoryArtifact.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1ArtifactoryArtifact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ArtifactoryArtifact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
