# coding: utf-8

"""
    Argo

    Python client for Argo Workflows  # noqa: E501

    OpenAPI spec version: master
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1S3Artifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        's3_bucket': 'V1alpha1S3Bucket'
    }

    attribute_map = {
        'key': 'key',
        's3_bucket': 's3Bucket'
    }

    def __init__(self, key=None, s3_bucket=None):  # noqa: E501
        """V1alpha1S3Artifact - a model defined in Swagger"""  # noqa: E501

        self._key = None
        self._s3_bucket = None
        self.discriminator = None

        if key is not None:
            self.key = key
        if s3_bucket is not None:
            self.s3_bucket = s3_bucket

    @property
    def key(self):
        """Gets the key of this V1alpha1S3Artifact.  # noqa: E501


        :return: The key of this V1alpha1S3Artifact.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this V1alpha1S3Artifact.


        :param key: The key of this V1alpha1S3Artifact.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def s3_bucket(self):
        """Gets the s3_bucket of this V1alpha1S3Artifact.  # noqa: E501


        :return: The s3_bucket of this V1alpha1S3Artifact.  # noqa: E501
        :rtype: V1alpha1S3Bucket
        """
        return self._s3_bucket

    @s3_bucket.setter
    def s3_bucket(self, s3_bucket):
        """Sets the s3_bucket of this V1alpha1S3Artifact.


        :param s3_bucket: The s3_bucket of this V1alpha1S3Artifact.  # noqa: E501
        :type: V1alpha1S3Bucket
        """

        self._s3_bucket = s3_bucket

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1S3Artifact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1S3Artifact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
