# coding: utf-8

"""
    Argo

    Python client for Argo Workflows  # noqa: E501

    OpenAPI spec version: master
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1WorkflowTemplateList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[V1alpha1WorkflowTemplate]',
        'metadata': 'V1ListMeta'
    }

    attribute_map = {
        'items': 'items',
        'metadata': 'metadata'
    }

    def __init__(self, items=None, metadata=None):  # noqa: E501
        """V1alpha1WorkflowTemplateList - a model defined in Swagger"""  # noqa: E501

        self._items = None
        self._metadata = None
        self.discriminator = None

        if items is not None:
            self.items = items
        if metadata is not None:
            self.metadata = metadata

    @property
    def items(self):
        """Gets the items of this V1alpha1WorkflowTemplateList.  # noqa: E501


        :return: The items of this V1alpha1WorkflowTemplateList.  # noqa: E501
        :rtype: list[V1alpha1WorkflowTemplate]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this V1alpha1WorkflowTemplateList.


        :param items: The items of this V1alpha1WorkflowTemplateList.  # noqa: E501
        :type: list[V1alpha1WorkflowTemplate]
        """

        self._items = items

    @property
    def metadata(self):
        """Gets the metadata of this V1alpha1WorkflowTemplateList.  # noqa: E501


        :return: The metadata of this V1alpha1WorkflowTemplateList.  # noqa: E501
        :rtype: V1ListMeta
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this V1alpha1WorkflowTemplateList.


        :param metadata: The metadata of this V1alpha1WorkflowTemplateList.  # noqa: E501
        :type: V1ListMeta
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1WorkflowTemplateList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1WorkflowTemplateList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
