# coding: utf-8

"""
    Argo

    Python client for Argo Workflows  # noqa: E501

    OpenAPI spec version: master
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1alpha1UserContainer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'container': 'V1Container',
        'mirror_volume_mounts': 'bool'
    }

    attribute_map = {
        'container': 'container',
        'mirror_volume_mounts': 'mirrorVolumeMounts'
    }

    def __init__(self, container=None, mirror_volume_mounts=None):  # noqa: E501
        """V1alpha1UserContainer - a model defined in Swagger"""  # noqa: E501

        self._container = None
        self._mirror_volume_mounts = None
        self.discriminator = None

        if container is not None:
            self.container = container
        if mirror_volume_mounts is not None:
            self.mirror_volume_mounts = mirror_volume_mounts

    @property
    def container(self):
        """Gets the container of this V1alpha1UserContainer.  # noqa: E501


        :return: The container of this V1alpha1UserContainer.  # noqa: E501
        :rtype: V1Container
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this V1alpha1UserContainer.


        :param container: The container of this V1alpha1UserContainer.  # noqa: E501
        :type: V1Container
        """

        self._container = container

    @property
    def mirror_volume_mounts(self):
        """Gets the mirror_volume_mounts of this V1alpha1UserContainer.  # noqa: E501


        :return: The mirror_volume_mounts of this V1alpha1UserContainer.  # noqa: E501
        :rtype: bool
        """
        return self._mirror_volume_mounts

    @mirror_volume_mounts.setter
    def mirror_volume_mounts(self, mirror_volume_mounts):
        """Sets the mirror_volume_mounts of this V1alpha1UserContainer.


        :param mirror_volume_mounts: The mirror_volume_mounts of this V1alpha1UserContainer.  # noqa: E501
        :type: bool
        """

        self._mirror_volume_mounts = mirror_volume_mounts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1UserContainer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1UserContainer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
